import { metadata, tagRecord, type WithoutMetadata } from './data-mode'
import type { Incident, AuditEntry, ResourceItem } from './incident-types'

const RAW_INITIAL_INCIDENTS: WithoutMetadata<Incident>[] = [
  {
    id: 'INC-4821',
    reportId: 'RPT-20481',
    city: 'Guwahati',
    state: 'Assam',
    location: 'Guwahati Â· Kamrup Metropolitan',
    lat: 26.1445,
    lng: 91.7362,
    coordinates: '26.1445Â° N, 91.7362Â° E',
    kind: 'flood',
    disasterType: 'Flood',
    severity: 'critical',
    status: 'escalating',
    verificationStatus: 'Verified',
    confidence: 97,
    description: 'Brahmaputra river exceeding danger mark by 1.4m. Inundation across wards 4, 7, and 11 with road access cut off near transit underpass.',
    source: 'State Emergency Operations Centre + Citizen cluster',
    updated: '2 min ago',
    duplicateCount: 14,
    duplicateMatch: 'INC-4821 Â· canonical incident',
    assignedTeam: 'Alpha-7',
    teams: 24,
    affected: '184,000',
    factors: [
      'Brahmaputra gauge exceeding danger mark (+1.4m)',
      '14 corroborating citizen flood reports within 1.2km',
      'High population exposure in low-lying wards',
      'Historical embankment vulnerability sector',
      'Optical & radar satellite flood boundary confirmed',
    ],
    evidence: [
      {
        source: 'Citizen report cluster',
        timestamp: '14:32:08 IST',
        location: 'Guwahati underpass corridor',
        summary: '14 nearby reports describe rapidly rising water and blocked access.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Central Water Commission gauge telemetry',
        timestamp: '14:28:15 IST',
        location: 'Brahmaputra Guwahati station',
        summary: 'River level 49.8m (danger mark: 48.4m), rising 4cm/hr.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'High-resolution satellite pass',
        timestamp: '14:15:00 IST',
        location: 'Kamrup floodplain',
        summary: 'Surface water extent expanded 32% compared to baseline pass.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Traffic CCTV camera feed',
        timestamp: '14:30:22 IST',
        location: 'GS Road underpass',
        summary: 'Camera view partially obscured by heavy rain, vehicle submergence confirmed.',
        reliability: 'Medium',
        supports: false,
        verification: 'illustrative',
      },
    ],
    evidenceSource: 'CWC Telemetry + Citizen report cluster Â· evidence preview',
    aiRecommendation: {
      action: 'Evacuate low-lying wards (4, 7, 11) within 90 minutes and dispatch 4 NDRF boat units.',
      reason: 'Sustained upstream discharge and high tide cycle ensure flood level will not recede before 20:00 IST.',
      evidenceSummary: 'Gauge telemetry, satellite inundation map, and 14 citizen reports all strongly align on critical water rise.',
      confidence: '97%',
      impact: '184,000 residents across 3 wards; arterial road cut off.',
      resources: ['4 NDRF Boat Units', 'Mobile Triage Unit 2', '24 Flood Barrier kits'],
      allocations: [
        { resource: 'NDRF Boat Unit 1 & 2', target: 'Guwahati Ward 4 & 7', reason: 'High population density near river bank + water rising 4cm/hr.' },
        { resource: 'Mobile Triage Unit 2', target: 'Kanaklata High School shelter', reason: 'Designated relief center with highest intake projection.' },
      ],
      allocationFactors: {
        severity: 'Critical',
        affected: '184,000 people',
        locationPriority: 'Brahmaputra embankment breach zone',
        availability: '6 rescue teams free in district',
      },
    },
    humanDecision: {
      status: 'Approved',
      finalAction: 'Evacuate low-lying wards (4, 7, 11) and deploy Alpha-7 NDRF unit.',
      timestamp: '12 min ago',
      actor: 'Admin Â· R. Chen',
      reason: 'Evidence cluster consistent and gauge telemetry confirmed critical threshold.',
    },
  },
  {
    id: 'INC-4816',
    reportId: 'RPT-20474',
    city: 'Puri',
    state: 'Odisha',
    location: 'Puri Â· Coastal District',
    lat: 19.8135,
    lng: 85.8312,
    coordinates: '19.8135Â° N, 85.8312Â° E',
    kind: 'cyclone',
    disasterType: 'Cyclone',
    severity: 'critical',
    status: 'escalating',
    verificationStatus: 'Verified',
    confidence: 95,
    description: 'Cyclone Aarav intensifying to Category 3 with sustained winds of 145 km/h. Storm surge warning issued for coastal blocks.',
    source: 'IMD Doppler Radar + Coastal sensors',
    updated: '4 min ago',
    duplicateCount: 9,
    duplicateMatch: 'INC-4816 Â· canonical incident',
    assignedTeam: 'Bravo-2',
    teams: 31,
    affected: '211,500',
    factors: [
      'Doppler radar indicates eye landfall within 6 hours',
      'Storm surge model projects 2.8m tidal wave along beach corridor',
      'Dense coastal settlement with temporary housing structures',
      'High wind hazard index across Puri-Konark belt',
    ],
    evidence: [
      {
        source: 'IMD Doppler Weather Radar Paradip',
        timestamp: '14:25:00 IST',
        location: 'Bay of Bengal Â· 120km off Puri',
        summary: 'Eye diameter 28km, central pressure 962 hPa, moving NW at 18 km/h.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Coastal tide gauge sensor',
        timestamp: '14:29:10 IST',
        location: 'Puri Beach Station',
        summary: 'Sea level elevated 1.9m above astronomical tide table.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Citizen mobile report cluster',
        timestamp: '14:31:40 IST',
        location: 'Puri Fishermen Colony',
        summary: 'Strong gusts causing roof collapses; power lines down on VIP Road.',
        reliability: 'Medium',
        supports: false,
        verification: 'illustrative',
      },
    ],
    evidenceSource: 'IMD Doppler Radar + Coastal Tide Sensor Â· evidence preview',
    aiRecommendation: {
      action: 'Complete mandatory evacuation of 5km coastal belt to cyclone shelters by 16:00 IST.',
      reason: 'Eye landfall projection within 6 hours with catastrophic surge risk.',
      evidenceSummary: 'Doppler radar track and tide gauge anomalies corroborate extreme cyclone category.',
      confidence: '95%',
      impact: '211,500 coastal residents; 14 multi-purpose cyclone shelters activated.',
      resources: ['31 ODRAF & NDRF teams', '18 Emergency Generators', '40,000 Food Packets'],
      allocations: [
        { resource: 'ODRAF Unit 3 & 4', target: 'Puri Grand Road corridor', reason: 'Clearing fallen trees from primary evacuation route to Jagannath shelter.' },
        { resource: 'NDRF Battalion 10', target: 'Astaranga & Brahmagiri coastal blocks', reason: 'Direct surge impact zone with low-elevation habitations.' },
      ],
      allocationFactors: {
        severity: 'Critical',
        affected: '211,500 people',
        locationPriority: 'Zero-elevation coastal buffer zone',
        availability: '31 teams deployed / 8 standby',
      },
    },
    humanDecision: {
      status: 'Approved',
      finalAction: 'Mandatory coastal evacuation authorized and ODRAF teams dispatched.',
      timestamp: '18 min ago',
      actor: 'District Collector Â· S. Mohanty',
      reason: 'Radar track confirmed Category 3 trajectory.',
    },
  },
  {
    id: 'INC-4809',
    reportId: 'RPT-20449',
    city: 'Kochi',
    state: 'Kerala',
    location: 'Kochi Â· Ernakulam District',
    lat: 9.9312,
    lng: 76.2673,
    coordinates: '9.9312Â° N, 76.2673Â° E',
    kind: 'flood',
    disasterType: 'Flood',
    severity: 'high',
    status: 'monitoring',
    verificationStatus: 'Verified',
    confidence: 93,
    description: 'Controlled release from Periyar reservoir causing overflow in low-lying Aluva and Kalamassery residential sectors.',
    source: 'Dam Safety Authority + Citizen reports',
    updated: '9 min ago',
    duplicateCount: 7,
    duplicateMatch: 'INC-4809 Â· canonical incident',
    assignedTeam: 'Echo-4',
    teams: 14,
    affected: '62,300',
    factors: [
      'Periyar reservoir at 91% capacity with 2 shutters opened',
      'Downstream urban wards experiencing backwater stagnation',
      'Dense commuter corridor along Edappally and Kakkanad',
      'Moderate to heavy rainfall forecast over catchment area',
    ],
    evidence: [
      {
        source: 'Dam Telemetry Stream',
        timestamp: '14:10:00 IST',
        location: 'Periyar River Basin',
        summary: 'Controlled discharge of 120 cumecs initiated as precautionary measure.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Citizen report cluster',
        timestamp: '14:24:33 IST',
        location: 'Kakkanad & Aluva',
        summary: 'Water entering ground floors of apartment complexes near riverbend.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Road camera snapshot',
        timestamp: '14:27:00 IST',
        location: 'Edappally junction',
        summary: 'Standing water of 40cm on outer service road, main flyover passable.',
        reliability: 'Medium',
        supports: false,
        verification: 'illustrative',
      },
    ],
    evidenceSource: 'Dam Safety Telemetry + Citizen cluster Â· evidence preview',
    aiRecommendation: {
      action: 'Deploy high-clearance pumps to Aluva underpasses and relocate 400 families to Kakkanad Relief Camp.',
      reason: 'Backwater influx combined with high tide will elevate localized water levels by 0.5m.',
      evidenceSummary: 'Discharge volumes and citizen reports verify inundation pattern.',
      confidence: '93%',
      impact: '62,300 residents in riverfront zones; localized power shutdowns.',
      resources: ['2 Rescue teams', 'Kakkanad shelter corridor', 'Mobile medical unit', '8 Submersible pumps'],
      allocations: [
        { resource: 'Kerala Fire & Rescue Unit 2', target: 'Aluva riverbank ward', reason: 'High vulnerability elderly population requiring boat transfer.' },
        { resource: 'Mobile medical unit', target: 'Kakkanad relief camp', reason: 'Pre-positioning for clean water distribution and wound dressing.' },
      ],
      allocationFactors: {
        severity: 'High',
        affected: '62,300 people',
        locationPriority: 'Downstream river bend residential zone',
        availability: '14 teams deployed / 4 available',
      },
    },
    humanDecision: {
      status: 'Approved',
      finalAction: 'High-clearance vehicles and rescue boats deployed to Aluva.',
      timestamp: '25 min ago',
      actor: 'Admin Â· J. Alvarez',
      reason: 'Discharge confirmed by dam control room.',
    },
  },
  {
    id: 'INC-4802',
    reportId: 'RPT-20462',
    city: 'Dehradun',
    state: 'Uttarakhand',
    location: 'Dehradun Â· Mussoorie Highway Corridor',
    lat: 30.3165,
    lng: 78.0322,
    coordinates: '30.3165Â° N, 78.0322Â° E',
    kind: 'quake',
    disasterType: 'Landslide',
    severity: 'high',
    status: 'monitoring',
    verificationStatus: 'Verified',
    confidence: 91,
    description: 'Major rockfall and slope subsidence blocking both carriageways on Mussoorie Road near Kolhukhet.',
    source: 'State Highway Patrol + Resident hotline',
    updated: '12 min ago',
    duplicateCount: 4,
    duplicateMatch: 'INC-4802 Â· canonical incident',
    assignedTeam: 'Delta-1',
    teams: 11,
    affected: '38,900',
    factors: [
      'Slope stability telemetry indicates continued soil creep',
      'Primary mountain transit route severed with ~180 vehicles queued',
      'Continued rainfall increasing mudflow hazard',
    ],
    evidence: [
      {
        source: 'Highway Patrol radio dispatch',
        timestamp: '13:18:04 IST',
        location: 'Kolhukhet kilometer 14',
        summary: 'Debris covering 60 meters of double-lane asphalt, earthmover required.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
      {
        source: 'Geological survey slope sensor',
        timestamp: '13:16:20 IST',
        location: 'Mussoorie ridge sector 3',
        summary: 'Tilt angle increased by 3.2 degrees following morning cloudburst.',
        reliability: 'High',
        supports: false,
        verification: 'illustrative',
      },
    ],
    evidenceSource: 'Highway Patrol + Slope Sensor Â· evidence preview',
    aiRecommendation: {
      action: 'Divert traffic via Hathipaon route and dispatch 2 heavy earthmovers for debris clearance.',
      reason: 'Unstable rock overhang requires controlled scaling before reopening highway.',
      evidenceSummary: 'Highway patrol on-site report and slope telemetry confirm total obstruction.',
      confidence: '91%',
      impact: '38,900 travelers and local residents affected by corridor closure.',
      resources: ['Heavy Earthmover 3 & 4', 'Slope Stabilization Crew', 'Traffic Diversion Unit'],
      allocations: [
        { resource: 'State PWD Earthmover', target: 'Mussoorie Road km 14', reason: 'Clearing 400 tons of boulder and mud debris.' },
      ],
      allocationFactors: {
        severity: 'High',
        affected: '38,900 people',
        locationPriority: 'Sole primary mountain highway',
        availability: '2 earthmovers active',
      },
    },
    humanDecision: {
      status: 'Approved',
      finalAction: 'Traffic diverted and heavy machinery dispatched.',
      timestamp: '30 min ago',
      actor: 'Admin Â· R. Chen',
      reason: 'Confirmed impassable by police patrol.',
    },
  },
  {
    id: 'INC-4795',
    city: 'Nagpur',
    state: 'Maharashtra',
    location: 'Nagpur Â· MIDC Industrial Area',
    lat: 21.1458,
    lng: 79.0882,
    coordinates: '21.1458Â° N, 79.0882Â° E',
    kind: 'fire',
    disasterType: 'Chemical spill',
    severity: 'moderate',
    status: 'contained',
    verificationStatus: 'Verified',
    confidence: 88,
    description: 'Industrial solvent leak and secondary storage fire contained by plant fire suppression systems.',
    source: 'Fire Department Telemetry',
    updated: '18 min ago',
    duplicateCount: 2,
    assignedTeam: 'Hazmat-3',
    teams: 6,
    affected: '9,400',
    factors: ['Hazardous chemical inventory report', 'Air quality sensors show localized VOC spike', 'Perimeter evacuation completed'],
    evidence: [
      { source: 'Industrial Safety Sensor', timestamp: '13:40:00 IST', location: 'MIDC Phase 2', summary: 'Solvent vapor concentration decreasing following foam blanket application.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'MIDC Sensor Stream',
    aiRecommendation: {
      action: 'Maintain 300m safety cordon and continue ambient air monitoring for 4 hours.',
      reason: 'Secondary flare-up risk minimal after chemical neutralizer deployment.',
      evidenceSummary: 'Air quality sensors and fire brigade confirmation demonstrate containment.',
      confidence: '88%',
      impact: '9,400 factory workers and nearby residents.',
      resources: ['Hazmat monitoring unit', 'Foam tender 4'],
      allocations: [{ resource: 'Hazmat monitoring unit', target: 'MIDC Phase 2', reason: 'Ongoing toxic vapor monitoring.' }],
      allocationFactors: { severity: 'Moderate', affected: '9,400 people', locationPriority: 'Industrial perimeter', availability: '6 teams on site' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Cordon maintained; situation stabilized.', timestamp: '40 min ago', actor: 'Admin Â· J. Alvarez' },
  },
  {
    id: 'INC-4788',
    city: 'Bhuj',
    state: 'Gujarat',
    location: 'Bhuj Â· Kutch District',
    lat: 23.242,
    lng: 69.6669,
    coordinates: '23.2420Â° N, 69.6669Â° E',
    kind: 'quake',
    disasterType: 'Earthquake',
    severity: 'moderate',
    status: 'monitoring',
    verificationStatus: 'Verified',
    confidence: 90,
    description: 'Magnitude 4.6 seismic tremor recorded 24km NE of Bhuj. Minor plaster damage reported, no structural collapses.',
    source: 'National Seismological Network',
    updated: '23 min ago',
    duplicateCount: 5,
    assignedTeam: 'Survey-1',
    teams: 8,
    affected: '14,200',
    factors: ['Seismic network epicenter calculation', 'Accelerograph readings in district capital', 'No critical utility disruptions'],
    evidence: [
      { source: 'National Seismological Network', timestamp: '13:30:12 IST', location: 'Kutch Fault Zone', summary: 'M4.6 at depth 12km; low aftershock probability.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Seismology Network',
    aiRecommendation: {
      action: 'Conduct visual structural inspection of masonry bridges and school buildings.',
      reason: 'Moderate intensity unlikely to cause deep foundation failures in retrofitted structures.',
      evidenceSummary: 'Seismic telemetry confirms moderate energy release.',
      confidence: '90%',
      impact: '14,200 residents in older district quarters.',
      resources: ['2 Structural Inspection Teams'],
      allocations: [{ resource: 'Structural Inspection Team', target: 'Bhuj Old City', reason: 'Checking unreinforced heritage masonry.' }],
      allocationFactors: { severity: 'Moderate', affected: '14,200 people', locationPriority: 'Old city quarter', availability: '8 teams on standby' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Engineers deployed for bridge and school checks.', timestamp: '50 min ago', actor: 'Admin Â· R. Chen' },
  },
  {
    id: 'INC-4781',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    location: 'Visakhapatnam Â· Port Area',
    lat: 17.6868,
    lng: 83.2185,
    coordinates: '17.6868Â° N, 83.2185Â° E',
    kind: 'cyclone',
    disasterType: 'Cyclone',
    severity: 'high',
    status: 'monitoring',
    verificationStatus: 'Verified',
    confidence: 94,
    description: 'Gale force winds of 90 km/h with heavy squalls affecting shipping operations and harbor infrastructure.',
    source: 'Port Trust Radar + Citizen reports',
    updated: '27 min ago',
    duplicateCount: 8,
    assignedTeam: 'Marine-2',
    teams: 19,
    affected: '97,800',
    factors: ['Outer spiral rainbands making landfall', 'Port authority suspended container terminal berths', 'Waterlogging along coastal highway'],
    evidence: [
      { source: 'Port Anemometer array', timestamp: '13:20:00 IST', location: 'Vizag Outer Harbour', summary: 'Peak gust 94 km/h, wave height 4.2m.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Port Authority Telemetry',
    aiRecommendation: {
      action: 'Suspend crane operations and reinforce shoreline defenses along Ramakrishna Beach.',
      reason: 'High wind shear and rising swell present acute hazard to harbor personnel.',
      evidenceSummary: 'Port sensors and IMD squall warnings coincide.',
      confidence: '94%',
      impact: '97,800 coastal residents and port workers.',
      resources: ['19 Response units', 'Harbor tugboats'],
      allocations: [{ resource: 'Disaster response team', target: 'Vizag Harbour Outer Wall', reason: 'Enforcing perimeter closure.' }],
      allocationFactors: { severity: 'High', affected: '97,800 people', locationPriority: 'Active port infrastructure', availability: '19 teams active' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Harbor operations suspended and teams pre-positioned.', timestamp: '1 hour ago', actor: 'Port Operations Lead' },
  },
  {
    id: 'INC-4774',
    city: 'Patna',
    state: 'Bihar',
    location: 'Patna Â· Ganga Riverfront',
    lat: 25.5941,
    lng: 85.1376,
    coordinates: '25.5941Â° N, 85.1376Â° E',
    kind: 'flood',
    disasterType: 'Flood',
    severity: 'critical',
    status: 'escalating',
    verificationStatus: 'Verified',
    confidence: 96,
    description: 'Ganga river flowing 1.1m above danger level. Drainage sluices backflowing into southern Patna residential colonies.',
    source: 'Central Water Commission + State Control Room',
    updated: '31 min ago',
    duplicateCount: 16,
    duplicateMatch: 'INC-4774 Â· canonical incident',
    assignedTeam: 'SDRF-1',
    teams: 22,
    affected: '156,700',
    factors: ['Ganga water level 50.4m (danger: 49.3m)', 'Sluice gate backflow in Kankarbagh and Rajendra Nagar', '16 citizen flood reports verified', 'Heavy rainfall continuing across catchment'],
    evidence: [
      { source: 'CWC Digha Ghat Telemetry', timestamp: '13:10:00 IST', location: 'Patna Ghats', summary: 'Ganga water level steady at 50.42m, highest of current monsoon season.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'CWC Telemetry Stream',
    aiRecommendation: {
      action: 'Operate emergency dewatering pump stations and evacuate Rajendra Nagar ground floor residents.',
      reason: 'River backflow preventing gravity drainage into Ganga; water will rise in southern wards.',
      evidenceSummary: 'Sluice telemetry and citizen reports confirm severe urban waterlogging.',
      confidence: '96%',
      impact: '156,700 residents in urban Patna.',
      resources: ['22 SDRF rescue boats', '12 Heavy dewatering pumps'],
      allocations: [{ resource: 'SDRF Boat Unit 5', target: 'Rajendra Nagar Ward 32', reason: 'Medical evacuation of stranded patients.' }],
      allocationFactors: { severity: 'Critical', affected: '156,700 people', locationPriority: 'Submerged hospital corridor', availability: '22 teams deployed' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Emergency pumping stations running at maximum capacity.', timestamp: '1.2 hours ago', actor: 'Admin Â· J. Alvarez' },
  },
  {
    id: 'INC-4767',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    location: 'Shimla Â· Ridge & Forest Sector',
    lat: 31.1048,
    lng: 77.1734,
    coordinates: '31.1048Â° N, 77.1734Â° E',
    kind: 'fire',
    disasterType: 'Wildfire',
    severity: 'moderate',
    status: 'contained',
    verificationStatus: 'Verified',
    confidence: 86,
    description: 'Pine forest ground fire near Tara Devi hill contained by forest department beat guards and fire tenders.',
    source: 'Forest Fire Telemetry (MODIS / VIIRS)',
    updated: '38 min ago',
    duplicateCount: 3,
    assignedTeam: 'Forest-4',
    teams: 5,
    affected: '4,100',
    factors: ['MODIS satellite thermal anomaly verified', 'Low wind speed aiding firebreak effectiveness', 'No residential encroachment'],
    evidence: [
      { source: 'VIIRS Satellite Thermal Detection', timestamp: '13:00:00 IST', location: 'Tara Devi Ridge', summary: 'Thermal signature cooling down; active front extinguished.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Satellite Thermal Feed',
    aiRecommendation: {
      action: 'Maintain thermal patrol along forest perimeter to prevent re-ignition from pine needles.',
      reason: 'Dry forest litter could rekindle if afternoon mountain winds pick up.',
      evidenceSummary: 'Satellite and beat officer confirmation show fire contained.',
      confidence: '86%',
      impact: '4,100 people in nearby village clusters.',
      resources: ['5 Forest fire personnel', '1 Tanker'],
      allocations: [{ resource: 'Forest Patrol', target: 'Tara Devi ridge', reason: 'Post-fire smolder watch.' }],
      allocationFactors: { severity: 'Moderate', affected: '4,100 people', locationPriority: 'Protected pine forest boundary', availability: '5 teams active' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Fire contained, fire line patrol established.', timestamp: '1.5 hours ago', actor: 'Divisional Forest Officer' },
  },
  {
    id: 'INC-4760',
    city: 'Chennai',
    state: 'Tamil Nadu',
    location: 'Chennai Â· Adyar & Velachery',
    lat: 13.0827,
    lng: 80.2707,
    coordinates: '13.0827Â° N, 80.2707Â° E',
    kind: 'flood',
    disasterType: 'Flood',
    severity: 'high',
    status: 'monitoring',
    verificationStatus: 'Verified',
    confidence: 92,
    description: 'Adyar river water level elevated following Chembarambakkam reservoir outflow. Velachery low-lying roads experiencing waterlogging.',
    source: 'Greater Chennai Corporation Sensors',
    updated: '44 min ago',
    duplicateCount: 11,
    assignedTeam: 'GCC-Rescue-8',
    teams: 17,
    affected: '74,600',
    factors: ['Chembarambakkam release rate 1,500 cusecs', 'Velachery stormwater drainage at 85% capacity', 'High tide delaying discharge into Bay of Bengal'],
    evidence: [
      { source: 'GCC Stormwater Sensor Network', timestamp: '12:50:00 IST', location: 'Velachery 100ft Road', summary: 'Water depth 25cm in low road pockets; main road open.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'GCC Sensor Network',
    aiRecommendation: {
      action: 'Deploy suction super-suckers to Velachery junction and monitor Adyar river gauge.',
      reason: 'Peak high tide at 17:30 IST may slow river outflow by 2 hours.',
      evidenceSummary: 'Sensor telemetry confirms localized accumulation without structural threat.',
      confidence: '92%',
      impact: '74,600 residents in Velachery and Madipakkam.',
      resources: ['17 Corporation response teams', '4 Super-sucker machines'],
      allocations: [{ resource: 'GCC Dewatering Team', target: 'Velachery Lake road', reason: 'Preventing water stagnation near residential streets.' }],
      allocationFactors: { severity: 'High', affected: '74,600 people', locationPriority: 'Dense residential basin', availability: '17 teams deployed' },
    },
    humanDecision: { status: 'Approved', finalAction: 'Corporation pumps operating; Adyar gauge under 24/7 watch.', timestamp: '2 hours ago', actor: 'GCC Control Room' },
  },
]

const RAW_INITIAL_VERIFICATION_QUEUE: WithoutMetadata<Incident>[] = [
  {
    id: 'RPT-20481',
    reportId: 'RPT-20481',
    city: 'Guwahati',
    state: 'Assam',
    location: 'Guwahati Â· Old Market & Underpass',
    lat: 26.1445,
    lng: 91.7362,
    coordinates: '26.1445Â° N, 91.7362Â° E',
    kind: 'flood',
    disasterType: 'Flood',
    severity: 'critical',
    status: 'pending',
    verificationStatus: 'Likely Genuine',
    confidence: 87,
    description: 'Water rising across three blocks near the transit underpass; 12 nearby reports corroborating rising flood level.',
    source: 'Citizen mobile report cluster',
    updated: '9 min ago',
    duplicateCount: 12,
    duplicateMatch: 'INC-4821 Â· canonical incident',
    assignedTeam: 'Unassigned',
    teams: 0,
    affected: '18,000',
    factors: ['Multiple nearby reports match pattern', 'Tight spatial and temporal cluster', 'Matches Brahmaputra flood wave'],
    evidence: [
      { source: 'Citizen report cluster', timestamp: '9 min ago', location: 'Old Market District', summary: '12 reports share a tight location and time window; one photo preview references the transit underpass.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Citizen report cluster Â· evidence preview',
    aiRecommendation: {
      action: 'Verify report and merge into canonical incident INC-4821.',
      reason: 'Matches active flood boundary in Kamrup.',
      evidenceSummary: 'High confidence spatial overlap.',
      confidence: '87%',
      impact: '18,000 residents in Old Market.',
      resources: ['2 Rescue Teams'],
    },
    humanDecision: {
      status: 'Pending',
      finalAction: 'Awaiting human review',
    },
  },
  {
    id: 'RPT-20474',
    reportId: 'RPT-20474',
    city: 'Puri',
    state: 'Odisha',
    location: 'Puri Â· Beach Road Corridor',
    lat: 19.8135,
    lng: 85.8312,
    coordinates: '19.8135Â° N, 85.8312Â° E',
    kind: 'cyclone',
    disasterType: 'Cyclone',
    severity: 'critical',
    status: 'pending',
    verificationStatus: 'Duplicate',
    confidence: 96,
    description: 'High winds tearing asbestos roofs on coastal road; duplicate of main cyclone incident.',
    source: 'Community alert channel',
    updated: '11 min ago',
    duplicateCount: 5,
    duplicateMatch: 'INC-4816 Â· canonical incident',
    assignedTeam: 'Unassigned',
    teams: 0,
    affected: '4,500',
    factors: ['Text and GPS overlap with INC-4816', 'No new independent casualties reported'],
    evidence: [
      { source: 'Report similarity match', timestamp: '11 min ago', location: 'Puri Beach Road', summary: 'Matching phrases and 180m distance from canonical report INC-4816.', reliability: 'High', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Report similarity match Â· AI evidence',
    aiRecommendation: {
      action: 'Confirm duplicate status and merge into canonical incident INC-4816.',
      reason: '96% semantic and coordinate overlap.',
      evidenceSummary: 'Corroborates active cyclone impact.',
      confidence: '96%',
      impact: 'Included in INC-4816 footprint.',
      resources: [],
    },
    humanDecision: {
      status: 'Pending',
      finalAction: 'Awaiting duplicate confirmation',
    },
  },
  {
    id: 'RPT-20462',
    reportId: 'RPT-20462',
    city: 'Dehradun',
    state: 'Uttarakhand',
    location: 'Dehradun Â· West Ridge Highway',
    lat: 30.3165,
    lng: 78.0322,
    coordinates: '30.3165Â° N, 78.0322Â° E',
    kind: 'quake',
    disasterType: 'Landslide',
    severity: 'moderate',
    status: 'pending',
    verificationStatus: 'Suspicious',
    confidence: 61,
    description: 'Urgent claim of bridge collapse near West Ridge, but single-source with no photos or corroboration.',
    source: 'Public message board',
    updated: '18 min ago',
    duplicateCount: 0,
    assignedTeam: 'Unassigned',
    teams: 0,
    affected: 'Unknown',
    factors: ['Single unverified source', 'Vague coordinate tag', 'No corroborating seismic or slope sensors'],
    evidence: [
      { source: 'Content signal review', timestamp: '18 min ago', location: 'West Ridge Highway', summary: 'Single-source text signal; location is broad and highway camera shows clear bridge.', reliability: 'Low', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Content signal review Â· AI evidence',
    aiRecommendation: {
      action: 'Flag as suspicious and hold in human review queue; do not dispatch emergency convoy.',
      reason: 'Low confidence (61%) and contradiction with highway camera feed.',
      evidenceSummary: 'Highway patrol camera confirms bridge is intact.',
      confidence: '61%',
      impact: 'Potentially misleading rumor.',
      resources: [],
    },
    humanDecision: {
      status: 'Pending',
      finalAction: 'Requires human review',
    },
  },
  {
    id: 'RPT-20449',
    reportId: 'RPT-20449',
    city: 'Kochi',
    state: 'Kerala',
    location: 'Kochi Â· Lakewood Residential Sector',
    lat: 9.9312,
    lng: 76.2673,
    coordinates: '9.9312Â° N, 76.2673Â° E',
    kind: 'fire',
    disasterType: 'Transformer fire',
    severity: 'high',
    status: 'pending',
    verificationStatus: 'Needs Human Review',
    confidence: 68,
    description: 'Transformer fire with smoke visible from residential streets; incomplete field confirmation.',
    source: 'Resident hotline note',
    updated: '32 min ago',
    duplicateCount: 3,
    assignedTeam: 'Unassigned',
    teams: 0,
    affected: '1,200',
    factors: ['Hotline report mentions smoke', 'Power grid telemetry shows localized sub-station trip'],
    evidence: [
      { source: 'Hotline note + grid status', timestamp: '32 min ago', location: 'Lakewood Sector', summary: 'Smoke mentioned by caller; electrical feeder 4 tripped at 13:58 IST.', reliability: 'Medium', supports: false, verification: 'illustrative' },
    ],
    evidenceSource: 'Hotline note + grid status Â· AI evidence',
    aiRecommendation: {
      action: 'Escalate to electrical utility and dispatch local fire tender for reconnaissance.',
      reason: 'Substation feeder trip corroborates reported transformer arc.',
      evidenceSummary: 'Medium reliability evidence warrants precautionary inspection.',
      confidence: '68%',
      impact: '1,200 residential consumers.',
      resources: ['1 Local Fire Tender'],
    },
    humanDecision: {
      status: 'Pending',
      finalAction: 'Escalation recommended',
    },
  },
]

const RAW_INITIAL_AUDIT_TRAIL: WithoutMetadata<AuditEntry>[] = [
  {
    id: 'AUD-9008',
    incident: 'INC-4816',
    action: 'Incident status updated to Escalating',
    actor: 'SANKET Bharat pipeline',
    actorType: 'AI',
    timestamp: '1 min ago',
    previousStatus: 'Dispatched',
    newStatus: 'Escalating',
    aiRecommendation: 'Update status once storm surge velocity exceeds 120 km/h.',
    humanDecision: 'Automated status sync',
    reason: 'Doppler radar confirmed eyewall pressure drop.',
  },
  {
    id: 'AUD-9007',
    incident: 'RPT-20449',
    action: 'Report escalated for Senior Review',
    actor: 'Admin Â· J. Alvarez',
    actorType: 'Human',
    timestamp: '4 min ago',
    previousStatus: 'Needs human review',
    newStatus: 'Escalated',
    aiRecommendation: 'Escalation recommended â€” incomplete evidence.',
    humanDecision: 'Escalated for fire brigade check',
    reason: 'Feeder trip confirmed transformer fire risk.',
  },
  {
    id: 'AUD-9006',
    incident: 'INC-4795',
    action: 'Recommendation modified by Admin',
    actor: 'Admin Â· R. Chen',
    actorType: 'Human',
    timestamp: '7 min ago',
    previousStatus: 'Pending review',
    newStatus: 'Contained',
    aiRecommendation: 'Escalate to critical chemical hazard.',
    humanDecision: 'Modified to moderate: contained with foam',
    reason: 'On-site responder confirmed solvent leak neutralized.',
    isOverride: true,
  },
  {
    id: 'AUD-9005',
    incident: 'INC-4809',
    action: 'Recommendation modified: Added medical triage point',
    actor: 'Admin Â· J. Alvarez',
    actorType: 'Human',
    timestamp: '9 min ago',
    previousStatus: 'Pending review',
    newStatus: 'Modified & verified',
    aiRecommendation: 'Dispatch boat rescue units only.',
    humanDecision: 'Modified to also pre-position mobile clinic at Kakkanad',
    reason: 'High proportion of elderly evacuees in flood corridor.',
    isOverride: true,
  },
  {
    id: 'AUD-9004',
    incident: 'INC-4821',
    action: 'Recommendation approved by Authority',
    actor: 'Admin Â· R. Chen',
    actorType: 'Human',
    timestamp: '12 min ago',
    previousStatus: 'Pending review',
    newStatus: 'Verified',
    aiRecommendation: 'Verify flood report; assign nearest rescue team Alpha-7.',
    humanDecision: 'Approved as recommended',
    reason: 'Brahmaputra gauge telemetry and 14 citizen reports confirmed rise.',
  },
  {
    id: 'AUD-9003',
    incident: 'RPT-20474',
    action: 'Duplicate report confirmed',
    actor: 'Admin Â· J. Alvarez',
    actorType: 'Human',
    timestamp: '15 min ago',
    previousStatus: 'Needs human review',
    newStatus: 'Duplicate',
    aiRecommendation: 'Likely duplicate of INC-4816 (96% match).',
    humanDecision: 'Confirmed as duplicate',
    reason: 'Verified matching coastal location and wind damage pattern.',
  },
  {
    id: 'AUD-9002',
    incident: 'RPT-20462',
    action: 'Report marked suspicious by AI',
    actor: 'SANKET Bharat model',
    actorType: 'AI',
    timestamp: '18 min ago',
    previousStatus: 'Incoming report',
    newStatus: 'Suspicious',
    aiRecommendation: 'Flag for human review â€” low confidence, single source.',
    humanDecision: 'Held in verification queue',
    reason: 'No corroborating photo or seismic sensor signal.',
  },
  {
    id: 'AUD-9001',
    incident: 'INC-4802',
    action: 'AI recommendation generated',
    actor: 'SANKET Bharat pipeline',
    actorType: 'AI',
    timestamp: '22 min ago',
    previousStatus: 'New report',
    newStatus: 'Pending review',
    aiRecommendation: 'Divert highway traffic and dispatch 2 earthmovers.',
    humanDecision: 'Not yet reviewed',
    reason: 'Slope subsidence confirmed on Mussoorie road.',
  },
]

const RAW_INITIAL_RESOURCES: WithoutMetadata<ResourceItem>[] = [
  { label: 'Rescue Teams', value: '18 / 24', detail: '6 available in reserve', iconName: 'Users', tone: 'cyan' },
  { label: 'Ambulances', value: '31 / 42', detail: '11 available on standby', iconName: 'Ambulance', tone: 'green' },
  { label: 'Medical Supplies', value: '78%', detail: 'Stock healthy across hubs', iconName: 'Package', tone: 'blue' },
  { label: 'Safe Shelters', value: '14 / 18', detail: '4 accepting new evacuees', iconName: 'HeartPulse', tone: 'amber' },
  { label: 'Emergency Vehicles', value: '26 / 36', detail: '10 available for dispatch', iconName: 'Truck', tone: 'violet' },
]


export const INITIAL_INCIDENTS: Incident[] = RAW_INITIAL_INCIDENTS.map((record, index) => demoSeed(record, 'INITIAL_INCIDENTS:' + index))

export const INITIAL_VERIFICATION_QUEUE: Incident[] = RAW_INITIAL_VERIFICATION_QUEUE.map((record, index) => demoSeed(record, 'INITIAL_VERIFICATION_QUEUE:' + index))

export const INITIAL_AUDIT_TRAIL: AuditEntry[] = RAW_INITIAL_AUDIT_TRAIL.map((record, index) => tagRecord({ ...record, action: 'Illustrative scenario event', actor: 'Fictional scenario actor', timestamp: 'Illustrative scenario time', previousStatus: 'Illustrative prior state', newStatus: 'Scenario only', humanDecision: 'No operational action', aiRecommendation: 'Illustrative proposal', reason: 'Seeded demo history; no action was performed.' }, metadata('demo', 'seed', 'INITIAL_AUDIT_TRAIL:' + index)) as AuditEntry)

export const INITIAL_RESOURCES: ResourceItem[] = RAW_INITIAL_RESOURCES.map((record, index) => tagRecord({ ...record, value: 'Not available', detail: 'No connected resource inventory' }, metadata('demo', 'seed', 'INITIAL_RESOURCES:' + index)) as ResourceItem)

function demoSeed(record: WithoutMetadata<Incident>, sourceId: string): Incident {
  return tagRecord({ ...record, isDemo: true, confidence: null, status: record.status === 'dispatched' ? 'monitoring' : record.status,
    source: 'Seeded demo scenario', updated: 'Illustrative scenario timestamp', teams: 0, assignedTeam: 'Not available',
    ...(record.verificationStatus === 'Duplicate' && record.duplicateMatch ? { canonicalCaseId: record.duplicateMatch.match(/INC-\d+/)?.[0] } : {}),
    duplicateMatch: record.duplicateMatch ? `Illustrative reference: ${record.duplicateMatch}` : undefined,
    factors: record.factors.map(f => `Illustrative: ${f}`),
    evidence: record.evidence.map(e => ({ ...e, source: `Illustrative: ${e.source}`, supports: false, verification: 'illustrative' as const, reliability: 'Unknown' as const })),
    aiRecommendation: { ...record.aiRecommendation, action: 'Review this fictional scenario and record a simulated recommendation decision.', reason: 'Seeded example; not model inference.', impact: `Illustrative scenario: ${record.aiRecommendation.impact}`,
      evidenceSummary: 'Illustrative source material; no independent corroboration.', confidence: 'Not available', resources: [], allocations: [],
      allocationFactors: { availability: 'Not available', distanceLocation: 'Unknown', recommendedTeamCount: 'Not available', responsePriority: 'Not assessed' } },
    humanDecision: { ...record.humanDecision, actor: 'Fictional scenario user', finalAction: 'Illustrative recommendation decision; no operational action.' },
  }, metadata('demo', 'seed', sourceId)) as Incident
}
